# Setup
title:               ImmigrationStory.uk
tagline:             'The costs and process of moving to the UK'
description:         'We’re a married couple from the Philippines who have gone through the process of immigrating and settling in the United Kingdom. Here you will find what our 6-year journey looked like; we hope that what we’re sharing here can guide you in yours.'
url:                 https://ImmigrationStory.uk
downloadbaseurl:     https://download-0553.immigrationstory.uk/request
baseurl:             ''
permalink:           /:categories/:title
future:              false

# About/contact
author:
  name:              Paolo Rodríguez
  url:               https://paolorodriguez.com
  email:             paolo@immigrationstory.uk

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom vars
version:             0.1.0
google_analytics_id: UA-175437265-1

# Front-matter defaults
defaults:
  - scope:
      path: ''
    values:
      locale: 'en-GB'
  - scope:
      path: 'en-gb'
    values:
      locale: 'en-GB'
  - scope:
      path: 'hi-in'
    values:
      locale: 'hi-IN'
  - scope:
      path: 'tl-ph'
    values:
      locale: 'tl-PH'

# Kramdown options
kramdown:
  toc_levels: "2"

# SASS options
sass:
  sass_dir: _sass
  sourcemap: development